import { Epilogue, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CustomNavbar from "@/components/CustomNavbar";
import Header from "@/components/Header";
import { Sora } from 'next/font/google';
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const sora = Sora({
  subsets: ['latin'], 
  weight: ['400', '500', '600', '700'],
  variable: '--font-sora',
});

const epilogue = Epilogue({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-epilogue',
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "School ERP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sora.variable} ${epilogue.variable} antialiased`}
      >
        <Header/>
        <CustomNavbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
